# Generated by Django 4.1.5 on 2023-03-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_column="TITLE", max_length=50)),
                ("content", models.CharField(db_column="CONTENT", max_length=3000)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="ClientEmail",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("email", models.CharField(db_column="EMAIL", max_length=50)),
            ],
        ),
    ]
