# Generated by Django 4.1.5 on 2023-03-10 00:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0005_alter_article_content_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=tinymce.models.HTMLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=tinymce.models.HTMLField(),
        ),
    ]
