# Generated by Django 4.1.5 on 2023-03-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0006_alter_article_content_alter_article_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.TextField()),
                ("lastName", models.TextField()),
                ("email", models.TextField()),
                ("subject", models.TextField()),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="lastModified",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="creationDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
